services:
  - type: web
    name: blacksite
    env: static
    buildCommand: npm run build
    staticPublishPath: out
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
